# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=35)),
                ('passwd', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=60)),
                ('address2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=10)),
                ('paynumber', models.CharField(max_length=16)),
                ('expmonth', models.CharField(max_length=2)),
                ('expyear', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PayDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paynumber', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=4)),
                ('expmonth', models.CharField(max_length=2)),
                ('expyear', models.CharField(max_length=4)),
            ],
        ),
    ]
